n1 = int(input('Digite o primeiro valor: '))
n2 = int(input('Digite o segundo valor: '))

print('A soma vale {}'.format(n1+n2))
print('A subtração vale {}'.format(n1-n2))
print('A multiplicação vale {}'.format(n1*n2))
print('A divisão vale {}'.format(n1/n2))
print('A divisão inteira vale {}'.format(n1//n2))
print('A exponenciação vale {}'.format(n1 ** n2))
print('As raízes quadradas valem aproximadamente {:.2f} e {:.2f}'.format(n1 ** (1/2), n2 ** (1/2)))
print('O módulo vale {}' .format(n1 % n2))