txt = str(input("Digite um texto: "))
print('O texto digitado foi: {}'.format(txt))
print('Esse texto é do tipo {}'.format(type(txt)))
print('Esse texto é alfabético? {}'.format(txt.isalpha()))
print('Esse texto é numérico? {}'.format(txt.isnumeric()))
print('Esse texto é alfanumérico? {}'.format(txt.isalnum()))
print('Esse texto é ASCII? {}'.format(txt.isascii()))
print('Esse texto é dígito? {}'.format(txt.isdigit()))
print('Esse texto é decimal? {}'.format(txt.isdecimal()))
print('Esse texto é identificador? {}'.format(txt.isidentifier()))
print('Esse texto está minúsculo? {}'.format(txt.islower()))
print('Esse texto está maiúsculo? {}'.format(txt.isupper()))
print('Esse texto é imprimível? {}'.format(txt.isprintable()))
print('Esse texto é espaço? {}'.format(txt.isspace()))
print('Esse texto é título? {}'.format(txt.istitle()))